### ISSUE TITLE
FTBFS: autolog.c:613:9: error: implicit declaration of function ‘re_comp’; did you mean ‘regcomp’? [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by MarcosFouces** [JKDingwall/autolog#2]
Hello
In the current state, autolog cannot be build on amd64.
Please check the details in the Debian bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1066269

Greetings, 
Marcos.

**Comment by JKDingwall** [comment]
Hi @MarcosFouces, thanks for the report.  This should be resolved in 0.42.1 in change eb6a8e0fea1ee6a88f71c94bc624132212d8d8b5.
